### ISSUE TITLE
The specified key does not exist

### ISSUE THREAD

**Issue by crizise** [aws-quickstart/quickstart-apache-superset#29]
Hello,
when I'm trying to deploy Apache Superset into a new VPC on AWS I'm facing this error:
![image](https://user-images.githubusercontent.com/17177904/134309374-fb231a56-3220-4eb0-a0d9-e6f632f2501f.png)
My IAM user has AmazonVPCFullAccess policy. 
Please advice.

**Comment by troy-ameigh** [comment]
How are you trying to deploy the Quick Start, are you deploying it from the landing page (see below). If you are forking or cloning from Github, you will need to copy it up to S3 and then change the QSS3BUCKETNAME Parameter to match the bucket you are launching from. Easiest way to launch is from the landing page, using the deployment links. 

Quick Start Landing Page: https://aws.amazon.com/quickstart/?quickstart-all.sort-by=item.additionalFields.updateDate&quickstart-all.sort-order=desc&solutions-all.sort-by=item.additionalFields.sortDate&solutions-all.sort-order=desc&awsf.filter-tech-category=*all&awsf.filter-industry=*all&awsf.filter-content-type=*all

SuperSet Landing Page: https://aws.amazon.com/quickstart/architecture/apache-superset/

SuperSet New VPC Deployment link: https://fwd.aws/q7qnb?

**Comment by crizise** [comment]
I tried to deploy this stack several times from different landing pages and the deployment link is the same as you mentioned:  https://fwd.aws/q7qnb?
I didn't fork anything just tried to follow this landing page: https://aws-quickstart.github.io/quickstart-apache-superset/ but stuck with the error. It looks like something with S3 bucket.
My IAM user has the _AmazonVPCFullAccess_ policy enabled. I tested this user and was able to create VPC and properties manually.

Anyway, I resolved my issue by 1) deploying the VPC stack with a template from [AWS CloudFormation VPC template
](https://docs.aws.amazon.com/codebuild/latest/userguide/cloudformation-vpc-template.html) AND 2) launching the second option [Deploy Apache Superset into an existing VPC on AWS](https://fwd.aws/jWBdy?)

**Comment by aseem-poloniex** [comment]
What availability zones should I be selecting?

**Comment by aseem-poloniex** [comment]
Hi,
I have created a [Video](https://youtu.be/s4G4ZmJWcY8) showing how to recreate the error mentioned in this post.

**Comment by troy-ameigh** [comment]
@aseem-poloniex Thank you for your issue. You need to change the "QSS3BucketRegion" parameter to match the region you are launching in. In this case it defaults to "cn-north-1" and you are trying to launch in "us-east-1". Make that change and it will launch fine. Thanks

**Comment by asafh-lb** [comment]
@troy-ameigh the Stack tries to load the aws-vpc.template.yaml from https://aws-quickstart.s3.cn-north-1.amazonaws.com/quickstart-aws-superset/submodules/quickstart-aws-vpc/templates/aws-vpc.template.yaml (or a different region as you suggest). The default region (as suggested to leave in the deployment guide) gives the same error as shown in this issue.
Changing it to us-west-2 as you suggested also is problematic, inspecting the resulting [url](https://aws-quickstart.s3.us-west-2.amazonaws.com/quickstart-aws-superset/submodules/quickstart-aws-vpc/templates/aws-vpc.template.yaml) shows S3 giving a PermanentRedirect to change to a global endpoint s3.amazonaws.com for the aws-quickstart bucket.
Inspecting that bucket shows the yaml file is just non-existent [there](https://aws-quickstart.s3.amazonaws.com/quickstart-aws-superset/submodules/quickstart-aws-vpc/templates/aws-vpc.template.yaml).

**Comment by troy-ameigh** [comment]
Issue is resolved.
