### ISSUE TITLE
Installing additional drivers with the quickstart

### ISSUE THREAD

**Issue by didia** [aws-quickstart/quickstart-apache-superset#31]
Hi, thank you for providing this great quickstart template for Apache superset.

I was wondering, is there a recommended way to install additional drivers for Apache Superset resources provided by the quickstart ?

At this moment, I was thinking of creating a new Dockerfile using the ECR image as parent and running pip install from there.

Could you recommend a better way to do this ?

**Comment by yike5460** [comment]
Hi, what specific driver you would to install and we will plan to add into further release. Currently the prebuilt drivers including common drivers like redshift, sql, clickhouse etc. and one consideration not to install full driver list is to make image as neat as possible.

**Comment by BlueStalker** [comment]
@yike5460 We have the similar issues, we want to install the snowflake sqlalchemy driver. Or generally is there a common way to do this? Can I start the template and install after?

**Comment by yike5460** [comment]
Quick workaround is to pack your own image based on official one in CloudFormation template, and replace image url in template after you had done the image
